name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: swift-actions/setup-swift@v3
      with:
        swift-version: '6.3.3'
    - name: Build and Test
      run: swift test
